[package]
name = "md2json2"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
collection_macros = "0.2.0"
serde = "1.0.216"
serde_derive = "1.0.216"
serde_json = "1.0.133"
sha2 = "0.10.8"
split-iter = "0.1.0"
strsim = "0.11.1"
take-until = "0.2.0"
walkdir = "*"
