[package]
name = "tiledownload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
image = { version = "0.25.6", features = ["png", "avif"] }
indicatif = "0.17.11"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["full"] }
