from os import system
import time
import sounddevice as sd
import numpy as np
import wave

# open dubia.cc/de/rosenkranz
# for (let item of document.querySelectorAll(".rosary-img a")) { item.remove(); }
# let s = []; let i = 0; for (let item of document.getElementsByClassName("rosary-img")) { let text = item.innerText.replaceAll(";", " ").replaceAll("\n", " ").replaceAll("\r", " ").replaceAll("...", "").replaceAll("'", "").replaceAll("\"", ""); if (text.trim().length == 0) { continue; } let secs = text.split(" ").length; s.push("system('say " + text + "')"); s.push("record_audio('./" + i + ".wav', " + Math.ceil(secs / 1.5) + ", sample_rate, device)"); i += 1; } let q = s.join("\r\n");console.log(q);

# pyython3 -m pip install --break-system-packages numpy sounddevice  

# Set parameters
duration = 10  # seconds
sample_rate = 44100  # 44.1 kHz standard audio
channels = 2  # Stereo
device = "Loopback"

# Recording function
def record_audio(filename, duration, sample_rate, device):
    print(f"Recording for {duration} seconds...")
    
    # Record audio
    audio = sd.rec(int(duration * sample_rate), samplerate=sample_rate, channels=channels, dtype=np.int16, device=device)
    sd.wait()  # Wait until recording is finished
    
    # Save to a WAV file
    with wave.open(filename, "wb") as wf:
        wf.setnchannels(channels)
        wf.setsampwidth(2)  # 16-bit audio
        wf.setframerate(sample_rate)
        wf.writeframes(audio.tobytes())
    
    print(f"Recording saved to {filename}")

# Start recording

time.sleep(2)

system('say "Hallo. Bitte sprich jeden Satz, den ich jetzt sagen werde, genau ein einziges Mal nach. Wiederhole keinen Satz, warte einfach ab bis ich wieder spreche. Sprich etwas schneller als normal. "')

time.sleep(6)

# ----------
system('say Im Namen des Vaters und des Sohnes und des Heiligen Geistes. Amen.  Ich glaube an Gott, den Vater, den Allmächtigen, den Schöpfer des Himmels und der Erde, ')
record_audio('./0.wav', 20, sample_rate, device)
system('say  und an Jesus Christus, seinen einziggeborenen Sohn, unsern Herrn, empfangen durch den Heiligen Geist,  geboren von der Jungfrau Maria, gelitten unter Pontius Pilatus, gekreuzigt, gestorben und begraben, ')
record_audio('./1.wav', 20, sample_rate, device)
system('say  hinabgestiegen in das Reich des Todes, am dritten Tage auferstanden von den Toten, aufgefahren in den Himmel   er sitzt zur Rechten Gottes, des allmächtigen Vaters  von dort wird er kommen, zu richten die Lebenden und die Toten.')
record_audio('./2.wav', 28, sample_rate, device)
system('say Ich glaube an den Heiligen Geist, die heilige katholische Kirche, Gemeinschaft der Heiligen,  Vergebung der Sünden, Auferstehung der Toten und das ewige Leben. Amen.')
record_audio('./3.wav', 17, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./4.wav', 37, sample_rate, device)
system('say Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes, der in uns den christlichen Glauben vermehre.  Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./5.wav', 32, sample_rate, device)
system('say Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes, der in uns die christliche Hoffnung stärke.  Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./6.wav', 32, sample_rate, device)
system('say Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes, der in uns die christliche Liebe entzünde.  Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./7.wav', 32, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./8.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./9.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./10.wav', 37, sample_rate, device)
system('say Der Engel Gabriel wurde von Gott. zu einer Jungfrau gesandt, die mit einem Mann namens Joseph aus dem Hause David verlobt war. Der Name der Jungfrau war Maria.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./11.wav', 53, sample_rate, device)
system('say Der Engel sagte zu ihr: Freue dich, du hochverehrte Tochter! Der Herr ist mit dir. Gesegnet bist du unter den Frauen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./12.wav', 48, sample_rate, device)
system('say Sie war tief beunruhigt über seine Worte und fragte sich, was sein Gruß zu bedeuten hatte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./13.wav', 45, sample_rate, device)
system('say Der Engel sagte zu ihr: Fürchte dich nicht, Maria. Du hast Gunst bei Gott gefunden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./14.wav', 44, sample_rate, device)
system('say Du wirst schwanger werden und einen Sohn gebären und ihm den Namen Jesus geben.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./15.wav', 44, sample_rate, device)
system('say Groß wird seine Würde sein, und man wird ihn Sohn des Höchsten nennen. Und seine Herrschaft wird ohne Ende sein.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./16.wav', 48, sample_rate, device)
system('say Maria sagte zu dem Engel: Wie kann das sein, da ich den Menschen nicht kenne?  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./17.wav', 44, sample_rate, device)
system('say Der Engel antwortete ihr: Der Heilige Geist wird über dich kommen, und die Kraft des Höchsten wird dich überschatten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./18.wav', 47, sample_rate, device)
system('say Der heilige Spross, der geboren werden soll, wird Sohn Gottes genannt werden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./19.wav', 42, sample_rate, device)
system('say Maria sagte: Ich bin die Dienerin des Herrn. Mir geschehe, wie du es sagst. Daraufhin verließ der Engel sie.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, vom Heiligen Geist empfangen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./20.wav', 47, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./21.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./22.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./23.wav', 37, sample_rate, device)
system('say Maria machte sich auf den Weg und ging eilig in das Bergland zu einer Stadt in Juda, wo sie in das Haus des Zacharias eintrat und Elisabeth begrüßte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./24.wav', 52, sample_rate, device)
system('say Als Elisabeth den Gruß Marias hörte, hüpfchte das Kind in ihrem Schoß.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./25.wav', 42, sample_rate, device)
system('say Elisabeth wurde mit dem Heiligen Geist erfüllt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./26.wav', 38, sample_rate, device)
system('say Sie rief mit lauter Stimme: Gesegnet bist du unter den Frauen und gesegnet ist die Frucht deines Leibes.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./27.wav', 46, sample_rate, device)
system('say Glücklich ist die, die darauf vertraut hat, dass sich die Worte des Herrn an sie erfüllen werden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./28.wav', 45, sample_rate, device)
system('say Dann sagte Maria: Mein Wesen verkündet die Größe des Herrn, mein Geist freut sich an Gott, meinem Retter.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./29.wav', 46, sample_rate, device)
system('say Denn er hat seine Magd in ihrer Niedrigkeit angesehen  alle künftigen Zeiten werden mich selig preisen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./30.wav', 45, sample_rate, device)
system('say Gott, der mächtig ist, hat Großes an mir getan  heilig ist sein Name.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./31.wav', 43, sample_rate, device)
system('say Seine Barmherzigkeit währt von Ewigkeit zu Ewigkeit über die, die ihn fürchten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./32.wav', 42, sample_rate, device)
system('say Maria blieb etwa drei Monate bei Elisabeth und kehrte dann nach Hause zurück.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, zu Elisabeth getragen hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./33.wav', 42, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./34.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./35.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./36.wav', 37, sample_rate, device)
system('say Plötzlich erschien ihm der Engel des Herrn im Traum und sagte zu ihm: Josef, Sohn Davids, fürchte dich nicht Durch den Heiligen Geist hat sie dieses Kind empfangen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./37.wav', 52, sample_rate, device)
system('say Sie wird einen Sohn bekommen, und du sollst ihm den Namen Jesus geben, weil er sein Volk von seinen Sünden erlösen wird.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./38.wav', 48, sample_rate, device)
system('say All dies geschah, um zu erfüllen, was der Herr durch den Propheten gesagt hat: Die Jungfrau wird schwanger sein und einen Sohn gebären, und sie werden ihn Emmanuel nennen, ein Name, der bedeutet: Gott ist mit uns.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./39.wav', 58, sample_rate, device)
system('say In jenen Tagen gab Cäsar Augustus ein Dekret heraus, das eine Volkszählung auf der ganzen Welt anordnete. Und so ging Josef nach Judäa, in die Davidstadt Bethlehem - denn er stammte aus dem Hause David -, um sich mit Maria, seiner Frau, die schwanger war, zu registrieren.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./40.wav', 65, sample_rate, device)
system('say Während sie dort waren, waren die Tage ihrer Gefangenschaft zu Ende. Sie gebar ihren erstgeborenen Sohn und wickelte ihn in Windeln und legte ihn in eine Krippe.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./41.wav', 52, sample_rate, device)
system('say In jener Gegend gab es Hirten, die auf den Feldern lebten und nachts über ihre Herden wachten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./42.wav', 45, sample_rate, device)
system('say Der Engel des Herrn erschien ihnen  und sie fürchteten sich sehr. Der Engel sagte zu ihnen: Ihr habt nichts zu befürchten!  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./43.wav', 48, sample_rate, device)
system('say Ich bin gekommen, um euch eine gute Nachricht zu verkünden, eine Nachricht, die große Freude auslöst. Heute ist euch in der Stadt Davids ein Retter geboren worden der Messias und Herr.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./44.wav', 54, sample_rate, device)
system('say Plötzlich war bei dem Engel eine große Schar der himmlischen Heerscharen, die Gott lobten und sagten: Ehre sei Gott in der Höhe, und Friede auf Erden denen, die sein Wohlgefallen haben.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./45.wav', 54, sample_rate, device)
system('say Sie eilten hin und fanden Maria und Josef und das Kind in der Krippe liegen  als sie es sahen, verstanden sie, was ihnen über dieses Kind gesagt worden war.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, in Bethlehem geboren hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./46.wav', 54, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./47.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./48.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./49.wav', 37, sample_rate, device)
system('say Als der Tag kam, an dem sie nach dem Gesetz des Mose gereinigt werden sollten, brachten sie ihn nach Jerusalem hinauf, um ihn dem Herrn zu opfern.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./50.wav', 52, sample_rate, device)
system('say Zu jener Zeit lebte in Jerusalem ein Mann namens Simeon. Er war gerecht und fromm. und der Heilige Geist war auf ihm.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./51.wav', 48, sample_rate, device)
system('say Ihm wurde durch den Heiligen Geist offenbart, dass er den Tod nicht erleben würde, bis er den Gesalbten des Herrn gesehen hätte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./52.wav', 48, sample_rate, device)
system('say Er kam nun, vom Geist beseelt, in den Tempel, und als die Eltern das Jesuskind hereinbrachten, nahm er es in seine Arme und segnete Gott.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./53.wav', 50, sample_rate, device)
system('say Nun, Meister, kannst du deinen Diener in Frieden entlassen  du hast dein Wort erfüllt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./54.wav', 44, sample_rate, device)
system('say Denn meine Augen haben deine Rettungstaten gesehen, die allen Völkern gezeigt wurden, damit sie sie sehen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./55.wav', 44, sample_rate, device)
system('say Simeon segnete sie und sagte zu Maria, seiner Mutter: Dieses Kind ist dazu bestimmt, der Untergang und der Aufstieg vieler in Israel zu sein, ein Zeichen, das bekämpft werden wird.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./56.wav', 54, sample_rate, device)
system('say Und du selbst sollst mit dem Schwert durchbohrt werden, damit die Gedanken vieler Herzen aufgedeckt werden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./57.wav', 44, sample_rate, device)
system('say Als die beiden alle Vorschriften des Gesetzes des Herrn erfüllt hatten, kehrten sie nach Galiläa und in ihre Heimatstadt Nazareth zurück.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./58.wav', 48, sample_rate, device)
system('say Das Kind wuchs an Größe und Kraft und war voller Weisheit, und die Gnade Gottes war auf ihm.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel aufgeopfert hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./59.wav', 46, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./60.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./61.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./62.wav', 37, sample_rate, device)
system('say Und als er zwölf Jahre alt war, gingen sie hinauf, um das Fest zu feiern, wie es Brauch war.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./63.wav', 46, sample_rate, device)
system('say Als sie am Ende des Festes zurückkehrten, blieb das Jesuskind ohne Wissen seiner Eltern zurück.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./64.wav', 44, sample_rate, device)
system('say In der Annahme, er sei in der Gruppe, setzten sie ihre Reise einen Tag lang fort und suchten ihn bei ihren Verwandten und Bekannten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./65.wav', 50, sample_rate, device)
system('say Als sie ihn nicht fanden, kehrten sie nach Jerusalem zurück, um ihn zu suchen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./66.wav', 43, sample_rate, device)
system('say Am dritten Tag trafen sie ihn im Tempel an, als er mitten unter den Lehrern saß. Alle, die ihn hörten, waren erstaunt über seine Klugheit und seine Antworten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./67.wav', 52, sample_rate, device)
system('say Und seine Mutter sagte zu ihm: Sohn, warum hast du uns das angetan? Du siehst doch, dass dein Vater und ich dich mit großer Sorge gesucht haben.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./68.wav', 52, sample_rate, device)
system('say Er sagte zu ihnen: Warum habt ihr mich gesucht? Wusstet ihr nicht, dass ich im Haus meines Vaters sein musste?  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./69.wav', 47, sample_rate, device)
system('say Aber sie begriffen nicht, was er zu ihnen sagte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./70.wav', 40, sample_rate, device)
system('say Da ging er mit ihnen hinab und kam nach Nazareth und war ihnen gehorsam.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./71.wav', 43, sample_rate, device)
system('say Seine Mutter aber behielt all diese Dinge im Gedächtnis. Jesus seinerseits machte stetig Fortschritte in Weisheit und Alter und Gnade vor Gott und den Menschen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, den du, o Jungfrau, im Tempel wiedergefunden hast. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./72.wav', 50, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./73.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./74.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./75.wav', 37, sample_rate, device)
system('say Dann ging Jesus mit ihnen zu einem Ort, der Gethsemane heißt und er begann, Kummer und Sorgen zu haben.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./76.wav', 45, sample_rate, device)
system('say Dann sagte er zu ihnen: Mein Herz ist fast zerbrochen vor Kummer. Bleibt hier und wacht mit mir.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./77.wav', 44, sample_rate, device)
system('say Er zog sich von ihnen zurück und kniete nieder, um zu beten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./78.wav', 40, sample_rate, device)
system('say Vater, wenn es möglich ist, lass diesen Kelch an mir vorübergehen. Doch es geschehe, wie du es willst, nicht wie ich es will.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./79.wav', 48, sample_rate, device)
system('say Als er zu seinen Jüngern zurückkehrte, fand er sie schlafend vor.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./80.wav', 40, sample_rate, device)
system('say Er sagte zu Petrus: Ihr konntet also nicht einmal eine Stunde mit mir wach bleiben?  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./81.wav', 42, sample_rate, device)
system('say In seiner Verzweiflung betete er noch intensiver. Ein Engel erschien ihm und kam vom Himmel, um ihm Kraft zu geben.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./82.wav', 46, sample_rate, device)
system('say Die Stunde ist gekommen, in der der Menschensohn der Macht der Bösen überantwortet werden soll.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./83.wav', 42, sample_rate, device)
system('say Während er noch sprach, kam Judas, einer der Zwölf, in Begleitung einer großen Menschenmenge mit Schwertern und Keulen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./84.wav', 44, sample_rate, device)
system('say Sofort ging er zu Jesus hinüber, sagte zu ihm: Friede, Rabbi, und umarmte ihn.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns Blut geschwitzt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./85.wav', 42, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./86.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./87.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./88.wav', 37, sample_rate, device)
system('say Sobald der Tag anbrach, fassten die Hohenpriester zusammen mit den Ältesten und Schriftgelehrten einen Beschluss. Sie banden Jesus, führten ihn ab und übergaben ihn an Pilatus.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./89.wav', 50, sample_rate, device)
system('say Pilatus verhörte ihn: Bist du der König der Juden? Jesus antwortete: Du sagst es.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./90.wav', 42, sample_rate, device)
system('say Pilatus nahm Jesus fest und ließ ihn geißeln.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./91.wav', 38, sample_rate, device)
system('say Von den Menschen verachtet und verworfen, ein Mann der Schmerzen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./92.wav', 39, sample_rate, device)
system('say Und doch waren die Leiden, die er trug, die unseren.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./93.wav', 39, sample_rate, device)
system('say Er wurde für unsere Fehler durchbohrt, für unsere Sünden zermalmt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./94.wav', 39, sample_rate, device)
system('say Sie verbanden ihm zuerst die Augen, schlugen ihn und verhöhnten ihn dann.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./95.wav', 40, sample_rate, device)
system('say Nachdem er Jesus gegeißelt hatte, übergab ihn Pilatus, um ihn zu kreuzigen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./96.wav', 40, sample_rate, device)
system('say Die Strafe, die uns Frieden brachte, lag auf ihm, und durch seine Wunden sind wir geheilt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./97.wav', 43, sample_rate, device)
system('say Er hat sein Leben als Sühneopfer gegeben, doch wird er Nachkommen sehen und lange leben.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns gegeißelt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./98.wav', 42, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./99.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./100.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./101.wav', 37, sample_rate, device)
system('say Die Soldaten führten Jesus nun in den Saal, der Prätorium genannt wurde, und versammelten die ganze Kohorte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./102.wav', 45, sample_rate, device)
system('say Sie kleideten ihn in königlichen Purpur, flochten eine Dornenkrone und setzten sie ihm auf.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./103.wav', 43, sample_rate, device)
system('say Sie fingen an, ihn zu grüßen: Gegrüßt seist du! König der Juden!  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./104.wav', 42, sample_rate, device)
system('say Sie schlugen Jesus immer wieder mit einem Rohr auf den Kopf und bespuckten ihn, beugten sich vor ihm nieder und taten so, als würden sie ihm huldigen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./105.wav', 52, sample_rate, device)
system('say Pilatus sagte zu der Menge: Seht zu, was ich tue. Ich werde ihn zu euch hinausführen, damit ihr erkennt, dass ich keinen Fall gegen ihn finde.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./106.wav', 51, sample_rate, device)
system('say Als Jesus herauskam und die Dornenkrone und den Purpurmantel trug, sagte Pilatus zu ihnen: Seht euch den Mann!  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./107.wav', 46, sample_rate, device)
system('say Als die Hohenpriester und die Tempelwächter ihn sahen, schrien sie: Kreuzige ihn! Kreuzige ihn!  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./108.wav', 43, sample_rate, device)
system('say Welches Verbrechen hat er denn begangen?, fragte Pilatus. Da schrien sie nur noch lauter: Kreuzige ihn!  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./109.wav', 44, sample_rate, device)
system('say Pilatus sagte zu den Juden: Seht euch euren König an!  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./110.wav', 40, sample_rate, device)
system('say Schließlich übergab Pilatus Jesus, damit er gekreuzigt werden konnte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns mit Dornen gekrönt worden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./111.wav', 40, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./112.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./113.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./114.wav', 37, sample_rate, device)
system('say Als sie damit fertig waren, ihn zum Narren zu halten, zogen sie Jesus den Mantel aus, kleideten ihn in seine eigenen und führten ihn zur Kreuzigung ab.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./115.wav', 52, sample_rate, device)
system('say Auf dem Weg nach draußen trafen sie einen Zyrenäer namens Simon. Diesen drängten sie zum Dienst, um das Kreuz zu tragen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./116.wav', 48, sample_rate, device)
system('say Eine große Menschenmenge folgte ihm, darunter auch Frauen, die sich an die Brust schlugen und über ihn klagten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./117.wav', 46, sample_rate, device)
system('say Jesus wandte sich an sie und sagte: Ihr Töchter Jerusalems, weint nicht um mich. Weint um euch selbst und um eure Kinder.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./118.wav', 48, sample_rate, device)
system('say Zwei andere Verbrecher wurden zusammen mit ihm zur Kreuzigung geführt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./119.wav', 40, sample_rate, device)
system('say Als sie an dem Ort ankamen, der Golgatha genannt wird, gaben sie ihm einen Trank aus Wein, der mit Galle gewürzt war  er kostete davon, weigerte sich aber zu trinken.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./120.wav', 54, sample_rate, device)
system('say Als sie ihn gekreuzigt hatten, teilten sie seine Kleider durch das Los unter sich auf  dann setzten sie sich dort nieder und wachten über ihn.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./121.wav', 51, sample_rate, device)
system('say Wer mein Nachfolger sein will, muss sich selbst verleugnen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./122.wav', 40, sample_rate, device)
system('say Er muss jeden Tag sein Kreuz auf sich nehmen und meinen Spuren folgen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./123.wav', 42, sample_rate, device)
system('say Wer sein Leben retten will, wird es verlieren  wer sein Leben um meinetwillen verliert, wird es retten.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns das schwere Kreuz getragen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./124.wav', 46, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./125.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./126.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./127.wav', 37, sample_rate, device)
system('say Jesus sagte: Vater, vergib ihnen, denn sie wissen nicht, was sie tun.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./128.wav', 41, sample_rate, device)
system('say Einer der Verbrecher sagte: Jesus, denk an mich, wenn du deine Herrschaft antrittst. Und Jesus antwortete: Ich versichere dir, dass du heute mit mir im Paradies sein wirst.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./129.wav', 52, sample_rate, device)
system('say Als Jesus seine Mutter mit dem Jünger, den er liebte, dort sah, sagte er zu seiner Mutter: Frau, da ist dein Sohn.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./130.wav', 48, sample_rate, device)
system('say Er sagte seinerseits zu dem Jünger: Da ist deine Mutter. Von dieser Stunde an nahm der Jünger sie in seine Sorge.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./131.wav', 47, sample_rate, device)
system('say Dann, gegen Mittag, rief Jesus laut: Mein Gott, mein Gott, warum hast du mich verlassen?  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./132.wav', 43, sample_rate, device)
system('say Als Jesus erkannte, dass nun alles zu Ende war, sagte er, um die Schrift zu erfüllen: Mich dürstet.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./133.wav', 45, sample_rate, device)
system('say Als Jesus den Wein nahm, sagte er: Nun ist es vollbracht.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./134.wav', 40, sample_rate, device)
system('say Jesus stieß einen lauten Schrei aus und sagte: Vater, in deine Hände befehle ich meinen Geist. Nachdem er dies gesagt hatte, verschied er.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./135.wav', 48, sample_rate, device)
system('say Finsternis kam über das ganze Land bis zum Nachmittag mit einer Verfinsterung der Sonne. Der Vorhang im Heiligtum wurde in zwei Teile zerrissen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./136.wav', 48, sample_rate, device)
system('say Sie nahmen den Leichnam Jesu und wickelten ihn nach jüdischem Brauch in ein Tuch.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der für uns am Kreuz gestorben ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./137.wav', 42, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./138.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./139.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./140.wav', 37, sample_rate, device)
system('say Nach dem Sabbat, als der erste Tag der Woche anbrach, kam Maria Magdalena mit den anderen Maria, um das Grab zu besichtigen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./141.wav', 47, sample_rate, device)
system('say Der Engel kam zu dem Stein, rollte ihn zur Seite und setzte sich darauf.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./142.wav', 42, sample_rate, device)
system('say Dann sprach der Engel zu den Frauen: Habt keine Angst. Ich weiß, dass ihr Jesus, den Gekreuzigten, sucht. Er ist nicht hier. Er ist auferstanden, wie er gesagt hat.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./143.wav', 52, sample_rate, device)
system('say Er ist von den Toten auferstanden und geht euch voraus nach Galiläa  dort werdet ihr ihn sehen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./144.wav', 44, sample_rate, device)
system('say Am Abend des ersten Tages der Woche, obwohl die Jünger die Türen des Ortes, an dem sie sich aufhielten, verschlossen hatten, kam Jesus und trat vor sie hin. Friede sei mit euch.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./145.wav', 54, sample_rate, device)
system('say In ihrer Panik und Angst dachten sie, sie sähen ein Gespenst.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./146.wav', 40, sample_rate, device)
system('say Er sagte zu ihnen: Warum seid ihr so erschrocken? Seht meine Hände und meine Füße an, ich bin es wirklich.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./147.wav', 46, sample_rate, device)
system('say Als die Jünger den Herrn sahen, freuten sie sich.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./148.wav', 38, sample_rate, device)
system('say Friede sei mit euch. Jesus sagte wieder. Wie mich der Vater gesandt hat, so sende ich euch.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./149.wav', 44, sample_rate, device)
system('say Ich bin die Auferstehung und das Leben  wer an mich glaubt, der wird leben, auch wenn er stirbt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der von den Toten auferstanden ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./150.wav', 45, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./151.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./152.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./153.wav', 37, sample_rate, device)
system('say Jesus führte seine Jünger hinaus in die Nähe von Bethanien und segnete sie mit erhobener Hand.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./154.wav', 43, sample_rate, device)
system('say Jesus wandte sich mit diesen Worten an sie: Mir ist alle Macht gegeben im Himmel und auf Erden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./155.wav', 44, sample_rate, device)
system('say Darum geht hin und macht alle Völker zu Jüngern. Tauft sie auf den Namen des Vaters und des Sohnes und des Heiligen Geistes.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./156.wav', 48, sample_rate, device)
system('say Und wisst, dass ich bei euch bin alle Tage bis zum Ende der Welt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./157.wav', 42, sample_rate, device)
system('say Wer an die gute Nachricht glaubt und die Taufe annimmt, wird gerettet  wer sich weigert, daran zu glauben, wird verdammt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./158.wav', 46, sample_rate, device)
system('say Als Jesus sie segnete, verließ er sie und wurde in den Himmel aufgenommen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./159.wav', 41, sample_rate, device)
system('say Er wurde vor ihren Augen in einer Wolke emporgehoben, die ihn ihren Blicken entzog.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./160.wav', 42, sample_rate, device)
system('say Dieser Jesus, der von euch genommen wurde, wird wiederkommen, so wie ihr ihn in den Himmel habt auffahren sehen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./161.wav', 45, sample_rate, device)
system('say Sie fielen nieder, um ihn zu ehren, und kehrten dann voller Freude nach Jerusalem zurück.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./162.wav', 42, sample_rate, device)
system('say Jesus nahm seinen Platz zur Rechten Gottes ein.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der in den Himmel aufgefahren ist. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./163.wav', 38, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./164.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./165.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./166.wav', 37, sample_rate, device)
system('say Jesus sagte: Ich werde den Vater bitten, und er wird euch einen anderen Beistand geben, der immer bei euch sein wird.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./167.wav', 47, sample_rate, device)
system('say Der Beistand, der Heilige Geist, den der Vater in meinem Namen senden wird, wird euch in allem unterweisen und euch an alles erinnern, was ich euch gesagt habe.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./168.wav', 52, sample_rate, device)
system('say In wenigen Tagen werdet ihr mit dem Heiligen Geist getauft werden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./169.wav', 40, sample_rate, device)
system('say Ihr werdet Kraft empfangen, wenn der Heilige Geist auf euch herabkommt  dann sollt ihr meine Zeugen sein in Jerusalem, in ganz Judäa. und bis an das Ende der Erde.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./170.wav', 53, sample_rate, device)
system('say Als der Pfingsttag kam, fanden sie sich an einem Ort versammelt. Plötzlich ertönte vom Himmel herab ein Brausen wie von einem starken Wind, das man im ganzen Haus hörte.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./171.wav', 52, sample_rate, device)
system('say Es erschienen Zungen wie von Feuer, die sich teilten und auf jeden von ihnen niedergingen. Alle wurden mit dem Heiligen Geist erfüllt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./172.wav', 48, sample_rate, device)
system('say Sie begannen, sich in fremden Sprachen auszudrücken und kühn zu verkünden, wie es der Geist ihnen eingab.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./173.wav', 44, sample_rate, device)
system('say Zu dieser Zeit hielten sich in Jerusalem fromme Männer aus allen Nationen auf. Diese hörten das Geräusch und versammelten sich in einer großen Menschenmenge. Sie waren verwirrt, denn jeder hörte die Jünger in seiner eigenen Sprache reden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./174.wav', 58, sample_rate, device)
system('say Petrus stand mit den Elf auf und sprach zu ihnen: Ihr müsst euch bekehren und taufen lassen, ein jeder von euch auf den Namen Jesu Christi, damit euch die Sünden vergeben werden  dann werdet ihr den Heiligen Geist empfangen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./175.wav', 60, sample_rate, device)
system('say Diejenigen, die seine Botschaft annahmen, ließen sich taufen  etwa dreitausend kamen an diesem Tag hinzu.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der uns den Heiligen Geist gesandt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./176.wav', 44, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./177.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./178.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./179.wav', 37, sample_rate, device)
system('say Gott, der Herr, sprach zu der Schlange: Ich will Feindschaft setzen zwischen dir und der Frau und zwischen deinen Nachkommen und ihren Nachkommen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./180.wav', 50, sample_rate, device)
system('say Er wird dir den Kopf zertreten, während du ihm in die Ferse beißt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./181.wav', 43, sample_rate, device)
system('say Ein großes Zeichen erschien am Himmel: eine Frau, bekleidet mit der Sonne und dem Mond unter ihren Füßen, und auf ihrem Haupt eine Krone mit zwölf Sternen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./182.wav', 52, sample_rate, device)
system('say Vater, alle, die du mir gegeben hast, will ich bei mir haben, wo ich bin.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./183.wav', 44, sample_rate, device)
system('say Darum ist sie unsere Mutter in der Ordnung der Gnade.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./184.wav', 41, sample_rate, device)
system('say In den Himmel aufgenommen, hat sie diese Heilspflicht nicht abgelegt, sondern fährt fort, uns durch ihre Fürbitte die Gaben des ewigen Heils zu bringen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./185.wav', 50, sample_rate, device)
system('say Denn er hat seine Dienerin in ihrer Niedrigkeit angesehen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./186.wav', 40, sample_rate, device)
system('say Alle künftigen Zeiten werden mich selig preisen.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./187.wav', 39, sample_rate, device)
system('say Wer mich liebt, den liebe ich auch, und wer mich sucht, der findet mich.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./188.wav', 44, sample_rate, device)
system('say Komm, meine Liebe. Meine Liebste, komm.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, in den Himmel aufgenommen hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./189.wav', 38, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./190.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./191.wav', 20, sample_rate, device)
system('say Vater Unser, der du bist im Himmel,  geheiligt werde dein Name,  dein Reich komme,  dein Wille geschehe,  wie im Himmel, so auch auf Erden.  Unser tägliches Brot gib uns heute  und vergib uns unsere Schuld,  wie auch wir vergeben unseren Schuldigern.  Und führe uns nicht in Versuchung,  sondern erlöse uns von dem Übel. Amen.')
record_audio('./192.wav', 37, sample_rate, device)
system('say Gott, der mächtig ist, hat große Dinge an mir getan.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./193.wav', 40, sample_rate, device)
system('say Mein Herz quillt über von einem guten Thema, während ich dem König meine Ode singe.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./194.wav', 44, sample_rate, device)
system('say Schöner bist du als die Menschenkinder  Gnade ist über deine Lippen ausgegossen  so hat Gott dich für immer gesegnet.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./195.wav', 48, sample_rate, device)
system('say O liebende Königin, du hast mir deine Güte gezeigt  du hast die Bitte meiner Unwürdigkeit nicht verachtet. Ich habe Herrlichkeit gesehen, die Sünder nicht sehen. Gelobt sei Gott, der durch dich die Reue der Sünder empfängt.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./196.wav', 58, sample_rate, device)
system('say Ich bin die Rose von Sharon, ich bin die Lilie der Täler.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./197.wav', 42, sample_rate, device)
system('say So hört nun, ihr Kinder, auf mich  Lehre und Weisheit verwerft nicht.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./198.wav', 42, sample_rate, device)
system('say Der Herr hat sie erwählt. Er hat sie erwählt, bevor sie geboren wurde.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./199.wav', 42, sample_rate, device)
system('say Ganz und gar heilig und frei von jedem Makel der Sünde.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./200.wav', 41, sample_rate, device)
system('say Höre, Tochter, und sieh, höre, vergiss dein Volk und deines Vaters Haus, und der König wird dir Schönheit geben  er ist dein Herr, wende dich zu ihm.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./201.wav', 52, sample_rate, device)
system('say Gesegnet bist du, Tochter, von Gott, dem Allerhöchsten, vor allen Frauen auf Erden.  Gegrüßet seiest du Maria, voll der Gnaden, der Herr ist mit dir. Du bist gebenedeit unter den Weibern und gebenedeit ist die Frucht deines Leibes Jesus, der dich, o Jungfrau, im Himmel gekrönt hat. Heilige Maria, Mutter Gottes, bitte für uns Sünder, jetzt und in der Stunde unseres Todes.')
record_audio('./202.wav', 42, sample_rate, device)
system('say Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,  wie es war im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen.')
record_audio('./203.wav', 18, sample_rate, device)
system('say Oh mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle,  führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.')
record_audio('./204.wav', 20, sample_rate, device)
system('say Sei gegrüßt, o Königin, Mutter der Barmherzigkeit  unser Leben, unsere Wonne und unsere Hoffnung, sei gegrüßt!  Zu dir rufen wir verbannte Kinder Evas  zu dir seufzen wir trauend und weinend in diesem Tal der Tränen.')
record_audio('./205.wav', 26, sample_rate, device)
system('say Wohlan denn, unsere Fürsprecherin, wende deine barmherzigen Augen uns zu und nach diesem Elend zeige uns Jesus, die gebenedeite Frucht deines Leibes!  O gütige, o milde, o süße Jungfrau Maria!  Im Namen des Vaters und des Sohnes und des Heiligen Geistes. Amen.')
record_audio('./206.wav', 30, sample_rate, device)
