[package]
name = "img2avif"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["rayon", "avif", "bmp", "jpeg", "png", "webp"]}
walkdir = "2.5.0"
